# **Input variables**

$t_{ex}$ $\rightarrow$ expected time \\
$t_{mes}$ $\rightarrow$ measured time \\

$t_{diff}$ $\rightarrow$ time difference between expected time ($t_{ex}$) and measured time ($t_{mes}$)


In [16]:
import numpy as ny

t_ex = 100
t_mes = 90
t_diff = t_ex - t_mes
print("t(diff)=", t_diff)

t(diff)= 10


# **normalization of $t_{diff}$** 
\\
how better or worse the player was compared to the given time

$t_{norm}=\frac{t_{diff}}{t_{ex}}$

In [15]:
t_norm = t_diff/t_ex
print("t(norm)=", t_norm)

t(norm)= 0.1


# **Input matrix**

Matrix $M_{[i,j]}\begin{vmatrix}
i\rightarrow answers \\ 
j \rightarrow tries
\end{vmatrix}$ and $i,j\in \{0,1\}$

In [14]:
vector_0 = ny.array([1, 0, 1, 1, 0])
vector_1 = ny.array([1, 1, 1, 1, 0])
vector_2 = ny.array([1, 1, 1, 1, 1])

#### add manually ########
vector_main = [vector_0, vector_1, vector_2]

vector_main_ny = ny.column_stack((vector_main[0], vector_main[1], vector_main[2]))
print("input matrix: \n", vector_main_ny)

input matrix: 
 [[1 1 1]
 [0 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 1]]


**log graph**

![log graph](https://www.intmath.com/blog/wp-content/images/2019/05/log10.png)

| x  | $log_{10}x$ |
|----|-------------|
| 1  | 0           |
| 2  | 0.301030    |
| 3  | 0.477121    |
| 4  | 0.602060    |
| 5  | 0.698970    |
| 6  | 0.778151    |
| 7  | 0.845098    |
| 8  | 0.903090    |
| 9  | 0.954243    |
| 10 | 1           |



In [6]:
log_array = [1, 0.954243, 0.903090, 0.845098, 0.778151, 0.698970, 0.602060, 0.477121, 0.301030, 0]

$n \in \{10, ..., 1\}$ \\
$r \rightarrow log_{10}(n) = lg (n)$


$K = \varnothing (r * M_{[i,j]})$ \\
$K| 0 < K < 1 $ \\

every column of matrix will be multiplied by a runnung integer n as n-1: \\
$K = \begin{bmatrix}
 r_{10}*X_{1,1}& . & . & . &r_{1}*X_{1,j} \\ 
 .&  &  &  & \\ 
 .&  &  &  & \\ 
 .&  &  &  & \\ 
 r_{10}*X_{i,1}& . & . & . &r_{1}*X_{i,j}
\end{bmatrix} = \begin{bmatrix}
 Y_{1,1}& . & . & . &Y_{1,j} \\ 
 .&  &  &  & \\ 
 .&  &  &  & \\ 
 .&  &  &  & \\ 
 Y_{i,1}& . & . & . &Y_{i,j}
\end{bmatrix} = \begin{bmatrix}
\varnothing (Y_{1,1};...;Y_{1,j})\\ 
.\\ 
.\\ 
.\\ 
\varnothing (Y_{i,1};...;Y_{i,j})
\end{bmatrix} = \begin{bmatrix}
Z_1\\ 
.\\ 
.\\ 
.\\ 
Z_l
\end{bmatrix} = \varnothing (Z_1; ...; Z_l)$


In [10]:
vector_conc = []
for i in range (0, len(vector_main)):
    vector_conc.extend([ny.multiply(log_array[i],vector_main[i])])


#### add manually ########
matrix = ny.column_stack((vector_conc[0], vector_conc[1], vector_conc[2]))
print(matrix)

matrix_mean = ny.matrix(matrix).mean()
print("\n K=", matrix_mean)

[[1.   0.95 0.9 ]
 [0.   0.95 0.9 ]
 [1.   0.95 0.9 ]
 [1.   0.95 0.9 ]
 [0.   0.   0.9 ]]

 K= 0.7533333333333334


# **reward or punish the user with $t_{norm}$**

$R_{reward} = f(t_{norm})=W_{reward} * t_{norm}$ \\
$W_{reward} = 0.1$ 

In [12]:
r_reward = 0.1*t_norm
print("R(reward)=", r_reward)

R(reward)= 0.010000000000000002


# Adaptivity factor

$W_{matrix} = 0.9$ \\
$AF$ $\rightarrow$ Adaptivity factor  

$AF = R_{reward} + W_{matrix}*K$ 



In [19]:
result = r_reward + 0.9 * matrix_mean
print("Adaptivity factor: ", result)

Adaptivity factor:  0.6880000000000001
